version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=myusername
      - POSTGRES_DB=law
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    profiles:
      - prod
    ports: 
      - 6789:6789
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    profiles:
      - prod
    depends_on:
      - backend


volumes:
  postgres-volume:
  chroma-data: