version: '3.9'

services:
  postgres:
    image: postgres:alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=myusername
      - POSTGRES_DB=law

volumes:
  postgres-volume: