version: '3.9'

services:
  postgres:
    image: postgres:alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=myusername
      - POSTGRES_DB=law
  chroma:
    image: chromadb/chroma:0.5.10
    ports:
      - 8000:8000
    volumes:
      - chroma-data:/chroma/chroma
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 6789:6789
    depends_on:
      - postgres
      - chroma
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend


volumes:
  postgres-volume:
  chroma-data: